### ISSUE TITLE
Can this be used with multiple client-ids?

### ISSUE THREAD

**Issue by bdparrish** [8gears/keycloak-auth-proxy#4]
Your setup looks to only be usable with a single app setup.  Is there a configuration example for multiple app setup behind NGINX?

**Comment by Vad1mo** [comment]
no, its not the way it should work for the use cases IMHO.  If you wan't multiple applications you should maybe look a real API Gateway.  Also with that little overhead in terms of resources it should be no problem to deploy it a dozen times.

**Comment by Vad1mo** [comment]
FYI: I'am referring to the  goproxy, which is in it respective branch
